blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(("userprofile.urls", 'userprofile'), namespace='userprofile')),
    path('comment/', include(("comment.urls", 'comment'), namespace='comment')),
    path('', include(("jimblog.urls", 'jimblog'), namespace='jimblog')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.contrib import admin
from django.urls import path
from .views import user_login
from .views import user_logout
from .views import user_delete, register

urlpatterns = [
    path('login/', user_login, name="login"),
    path('logout/', user_logout, name="logout"),
    path('userdelete/<int:id>/', user_delete, name="userdelete"),
    path('register/', register, name="register"),
]

userprofile/models.py
from django.db import models

# Create your models here.

userprofile/forms.py
from django import forms
from django.contrib.auth.models import User


class User_Login_Form(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


class User_Register_Form(forms.ModelForm):
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError('两次密码输入不一致')

userprofile/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .forms import User_Login_Form, User_Register_Form
from django.contrib.auth.decorators import login_required


def user_login(request):
    if request.method == 'POST':
        user_login_form = User_Login_Form(request.POST)
        if user_login_form.is_valid():
            data = user_login_form.cleaned_data
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                login(request, user)
                return redirect('jimblog:home')
            else:
                return HttpResponse("用户名密码错误")
        else:
            return HttpResponse("输入的数据不合法")
    elif request.method == 'GET':
        user_login_form = User_Login_Form()
        return render(request, 'userprofile/login.html', {'form': user_login_form})
    else:
        return HttpResponse("请适用GET或POST方法")


@login_required(login_url='/user/login/')
def user_logout(request):
    logout(request)
    return redirect('jimblog:home')


@login_required(login_url='/user/login/')
def user_delete(request, id):
    if request.method == 'POST':
        user = User.objects.get(id=id)
        if request.user == user:
            logout(request)
            user.delete()
            return redirect('jimblog:home')
        else:
            return HttpResponse('登录用户与删除用户不一致')
    else:
        return HttpResponse('请使用POST方法')


def register(request):
    if request.method == 'POST':
        user_register_form = User_Register_Form(data=request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)
            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()
            login(request, new_user)
            return redirect('jimblog:home')
        else:
            return HttpResponse('注册表单有误')
    elif request.method == 'GET':
        user_register_form = User_Register_Form()
        return render(request, 'userprofile/register.html', {'form': user_register_form})
    else:
        return HttpResponse('请使用GET/POST方法')

templates/userprofile/login.html
{% extends 'blog/base.html' %}
{% block detail %}

<div class="col-4">
    <form method="post" action=".">
        {% csrf_token %}
        <div class="form-group">
            <label for="username">用户名</label>
            <input type="text" class="form-control" id="username" name="username">
        </div>
        <div class="form-group">
            <label for="password">密码</label>
            <input type="password" class="form-control" id="password" name="password">
        </div>
        <button type="submit" class="btn btn-primary">提交</button>
    </form>
    没有账号？<a href="{% url 'userprofile:register' %}">注册</a>
</div>

{% endblock %}

templates/userprofile/register.html
{% extends 'blog/base.html' %}
{% block detail %}
    <div class="col-8">
<form method="post" action=".">
{% csrf_token %}
    <hr>
<div class="form-group form-inline">
    <label for="username" style="width: 90px; padding-right: 10px">用户名</label>
    <input class="form-control" id="username" name="username" type="text" required>
</div>
    <div class="form-group form-inline">
        <label for="email" style="width: 90px; padding-right: 10px">邮箱</label>
        <input class="form-control" id="email" name="email" type="text">
    </div>
    <div class="form-group form-inline">
        <label for="password" style="width: 90px; padding-right: 10px">密码</label>
        <input class="form-control" id="password" name="password" type="password" required>
    </div>
    <div class="form-group form-inline">
        <label for="password2" style="width: 90px; padding-right: 10px">确认密码</label>
        <input class="form-control" id="password2" name="password2" type="password" required>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-secondary" style="margin-left: 90px">提交</button>
        <button type="reset" class="btn btn-secondary" style="margin-left: 90px">取消</button>
    </div>
</form>
    </div>
{% endblock %}