blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(("userprofile.urls", 'userprofile'), namespace='userprofile')),
    path('comment/', include(("comment.urls", 'comment'), namespace='comment')),
    path('', include(("jimblog.urls", 'jimblog'), namespace='jimblog')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    path('comment/<int:article_id>/', views.comment, name='post_comment'),
]

jimblog/urls.py
from django.contrib import admin
from django.urls import path
from jimblog.views import show_article, show_article_all, article_create, article_detail, article_modify, article_delete, article_column


urlpatterns = [
    path('', show_article, name="home"),
    path('all/', show_article_all, name="all"),
    path('articlecreate/', article_create, name="article_create"),
    path('article/<int:id>', article_detail, name="detail"),
    path('articlemodify/<int:id>/', article_modify, name="modify"),
    path('articledelete/<int:id>/', article_delete, name="delete"),
    path('column', article_column, name='topic')
]

userprofile/urls.py
from django.contrib import admin
from django.urls import path
from .views import user_login
from .views import user_logout
from .views import user_delete, register

urlpatterns = [
    path('login/', user_login, name="login"),
    path('logout/', user_logout, name="logout"),
    path('userdelete/<int:id>/', user_delete, name="userdelete"),
    path('register/', register, name="register"),
]

templates/blog/all.html
{% extends "blog/base.html" %}
{% block detail %}
    <div class="col-9">
    <h6 style="display: inline"><a href="{% url 'jimblog:all' %}?order=total_views&search={{ search }}&column={{ column }}&topic={{ topic }}" style="color: gray">最热 /</a></h6><h6 style="display: inline; color: gray;margin-left: 10px"><a href="{% url 'jimblog:all' %}?search={{ search }}&column={{ column }}&topic={{ topic }}" style="color: gray">最新</a></h6>
        {% for post in posts %}
            <div class="row">
            {% if post.avatar %}
            <div class="col-3">
            <img src="{{ post.avatar.url }}"
                 alt="avatar"
                 style="max-width: 100%; border-radius: 20px">
            </div>
                <div class="col-9">
            {% else %}
                <div class="col-9 offset-3">
                {% endif %}
        {% if post.column %}
            <button type='button' class="btn btn-sm mb-2
            {% if post.column.id == 1 %}
            btn-primary
            {% elif post.column.id == 2 %}
            btn-secondary
            {% endif %}">
            <a href="{% url 'jimblog:all' %}?search={{ search }}&column={{ post.column.id }}&topic={{ tag }}" style="color: white">{{ post.column }}</a>
            </button>
        {% endif %}
            <span>
        {% for tag in post.topic.all %}
        <a href="{% url 'jimblog:all' %}?search={{ search }}&column={{ post.column.id }}&topic={{ tag }}" class="badge-secondary">{{ tag }}</a>
    {% endfor %}
    </span>
        <h1><a href="{% url 'jimblog:detail' post.id %}" style="color: black">{{ post.title }}</a></h1>
            <hr>
        <p>{{ post.body | truncatechars:50 }}</p>
            <p class="small text-right text-muted"><i class="fa fa-pencil" style="color: green"></i> {{ post.author }} <i class="fa fa-clock-o" style="color: cornflowerblue"></i>{{ post.updated.date }} <i class="fa fa-eye" style="color: mediumpurple"></i> {{ post.total_views }}</p>
            <hr>
            </div>
        </div>
        {% endfor %}

        <div class="pagination">
            <div class="m-auto">
        <span class="page-link">
            {% if posts.has_previous %}
                <a href="?page=1&order={{ order }}&search={{ search }}&column={{ column }}&topic={{ topic }}" class="btn btn-light">
                &laquo; 1
                </a>
                <span>...</span>
                <a href="?page={{ posts.previous_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&topic={{ topic }}" class="btn btn-light">
                {{ posts.previous_page_number }}
                </a>
            {% endif %}
            <span class="current-app btn btn-dark btn-lg">
            {{ posts.number }}
        </span>
            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}&order={{ order }}&search={{ search }}&column={{ column }}&topic={{ topic }}" class="btn btn-light">
            {{ posts.next_page_number }}
            </a>
                <span>...</span>
                <a href="?page={{ posts.paginator.num_pages }}&order={{ order }}&search={{ search }}&column={{ column }}&topic={{ topic }}" class="btn btn-light">
            {{ posts.paginator.num_pages}} &raquo;
            </a>
            {% endif %}
        </span>
            </div>
        </div>
    </div>
    </div>


{% endblock %}

templates/blog/article_create.html
{% extends "blog/base.html" %}
{% block detail %}
<div class="col-xs-12 col-lg-8">
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">文章标题</label>
            <input type="text" class="form-control" id="title" name="title">
        </div>
        <div class="form-group">
            <label for="body">文章正文</label>
            <textarea type="text" class="form-control" id="body" name="body" rows="12"></textarea>
        </div>
        <div class="form-group">
            <label for="topic">标签</label>
            <input type="text" class="form-control" id="topic" name="topic">
        </div>
        <div class="form-group">
            <label for="topic">栏目</label>
            <select class="form-control" id="column" name="column">
                <option value="none">请选择栏目</option>
                {% for column in columns %}
                <option value="{{ column.id }}">{{ column }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="avatar">标题图</label>
            <input type="file" class="form-control-file" id="avatar" name="avatar">
        </div>
        <button type="submit" class="btn btn-primary">完成</button>
    </form>
</div>
{% endblock %}

templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.staticfile.org/twitter-bootstrap/4.5.3/css/bootstrap.css" rel="stylesheet">
    <link href="https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    <link rel="stylesheet" href="{% static 'calendar_css/calendar.css' %}">
    <link rel="stylesheet" href="{% static 'md_css/maize.css' %}">
    <script src="https://cdn.staticfile.org/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.5.3/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.5.3/js/bootstrap.min.js"></script>
    <script src="https://cdn.staticfile.org/layer/3.1.1/layer.js"></script>
    <script src="{% static 'script/blog.js' %}"></script>
    <title>Jim Home</title>
    <style>
        #header

        {
            background-image: url("{% static 'image/home1.jpg' %}");
        }
    </style>
</head>
<body>
<div class="container-fluid">
    {% include "blog/header.html" %}
    <div class="row">
        <div id="header" class="col-12">
            <h1 class="display-5 font-weight-bold text-center text-muted">吉 姆 的 小 屋</h1>
        </div>
    </div>
    <div class="row">
        {% include "blog/home-left.html" %}
        {% block detail %}
        {% endblock %}
    </div>
</div>
</body>
</html>

templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load djangomarkdown %}
{% block detail %}

    <div class="col-9">
    <h1 style="display: inline">{{ post.title }}</h1>

        {% if post.author.id == user.id %}
        <h4 style="display: inline;padding: 30px"><a class="h6" style="color: gray" href="{% url 'jimblog:modify' post.id %}">修改文章</a></h4>
            <h4 style="display: inline;padding: 30px"><a class="h6" style="color: gray" href="#" onclick="confirm_delete()">删除文章</a></h4>
        {% endif %}

    <hr>
        {% if post.column %}
            <button type='button' class="btn btn-sm mb-2
            {% if post.column.id == 1 %}
            btn-primary
            {% elif post.column.id == 2 %}
            btn-secondary
            {% endif %}">
                {{ post.column }}
            </button>
        {% endif %}
    <span>
        {% for tag in post.topic.all %}
        <a href="#" class="badge-secondary">{{ tag }}</a>
    {% endfor %}
    </span>
    <div class="text-left" id="write">{{ post.body | djangomarkdown }}</div>
    <p class="small text-right text-muted">Posted by {{ post.author }} {{ post.updated }} Views: {{ post.total_views }}</p>

    <hr>
    {% if user.is_authenticated %}
    <form
        action="{% url 'comment:post_comment' post.id %}"
        method="post"
        >
        {% csrf_token %}
        <div class="form-group">
            <label for="body">
                <strong>
                    我也要发言：
                </strong>
            </label>
            <div>
                {{ comment_form.media }}
                {{ comment_form.body }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">发送</button>
    </form>

    <br>
    {% else %}
    <br>
    <h5 class="row justify-content-center">
    请<a href="{% url 'userprofile:login' %}">登录</a>
    </h5>
    <br>
    {% endif %}

    <!-- 显示评论 -->
    <h4>共有{{ comments.count }}条评论</h4>

    {% for comment in comments %}
    <hr>
    <p>
        <strong style="color: pink">
            {{ comment.user }}
        </strong>于
        <span style="color: green">
            {{ comment.created|date:"Y-m-d H:i:s" }}
        </span>时说：
    </p>
    <pre style="font-family: inherit; font-size: 1em">
        {{ comment.body | safe }}
    </pre>
    {% endfor %}
    <form
            method="post"
            style="display: none"
            action="{% url 'jimblog:delete' post.id %}"
            id="delete"
    >
        {% csrf_token %}
        <button type="submit"></button>
    </form>
    </div>
    <script>
        $(".django-ckeditor-widget").removeAttr('style');
    </script>
{% endblock %}

templates/blog/header.html
<div class="row">
    <div class="col">
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'jimblog:home' %}" style="color: black; font-weight: bold">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'jimblog:topic' %}" style="color: black; font-weight: bold">Topic</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'jimblog:all' %}" style="color: black; font-weight: bold">All</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" style="color: black; font-weight: bold">About</a>
            </li>
        </ul>
    </div>
    <div class="col">
        <ul class="nav justify-content-end">
            <li class="nav-item">
                <form action="{% url 'jimblog:all' %}">
                    <input type="text" class="form-control" name="search" placeholder="搜索文章" required>
                </form>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                    <a class="btn btn-secondary btn-light dropdown-toggle" href="#" role="button" id="dropdownmenu" data-toggle='dropdown' aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
                    <div class="dropdown-menu" aria-labelledby="dropdownmenu">
                    <a class="dropdown-item" href="#">个人信息</a>
                    <a class="dropdown-item" href="#" onclick="user_delete()">删除用户</a>
                    <a class="dropdown-item" href="{% url 'userprofile:logout' %}">登出</a>
                    </div>
                    <form method="post" id="userdelete" style="display: none" action="{% url 'userprofile:userdelete' user.id %}">
                        {% csrf_token %}
                        <button type="submit"></button>
                    </form>
            </li>
                {% if user.id == 1 %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'jimblog:article_create' %}"><i class="fa fa-plus-square-o fa-lg" style="color: gray"></i></a>
                </li>
                    {% endif %}
                    {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userprofile:login' %}"><i class="fa fa-address-book-o fa-lg" style="color: gray"></i></a>
            </li>
            {% endif %}

            <li class="nav-item">
                <a class="nav-link" href="#"><i class="fa fa-qq fa-lg" style="color: gray"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="https://github.com/shenjingbiqd"><i class="fa fa-github fa-lg" style="color: gray"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"><i class="fa fa-envelope fa-lg" style="color: gray"></i></a>
            </li>
        </ul>
    </div>
</div>

templates/blog/home-left.html
<div class="col-lg-3 col-xs-0">
<div class="calendar-1">
    <div class="title">
        <a href="" id="prev" class="float-lg-left" style="font-size: xxx-large; color: deepskyblue"><</a>
        <a href="" id="next" class="float-lg-right" style="font-size: xxx-large; color: deepskyblue">></a>
        <h3 class="calendar-title" id="calendar-title">Month</h3>
        <h4 class="calendar-title-sub" id="calendar-year">Year</h4>
        <hr>
    </div>
    <div class="body">
        <div class="lightgray body-list">
            <ul>
                <li>MON</li>
                <li>TUE</li>
                <li>WED</li>
                <li>THU</li>
                <li>FRI</li>
                <li>SAT</li>
                <li>SUN</li>
            </ul>
        </div>
        <div class="darkgray body-list">
            <ul id="days">
            </ul>
        </div>
    </div>
</div>
</div>
{% load static %}
<script src="{% static 'script/calendar.js' %}"></script>

templates/blog/home.html
{% extends "blog/base.html" %}
{% block detail %}
    <div class="col-xs-12 col-lg-8">
        {% for post in posts %}
        <h1><a href="{% url 'jimblog:detail' post.id %}" style="color: black">{{ post.title }}</a></h1>
            <hr>
        <p>{{ post.body | truncatechars:50 }}</p>
            <p class="small text-right text-muted"><i class="fa fa-pencil" style="color: green"></i> {{ post.author }} <i class="fa fa-clock-o" style="color: cornflowerblue"></i> {{ post.updated.date }} <i class="fa fa-eye" style="color: mediumpurple"></i> {{ post.total_views }}</p>
            <hr>
        {% endfor %}
    </div>
{% endblock %}

templates/blog/modify.html
{% extends "blog/base.html" %}
{% block detail %}
    <div class="col-sm-12 col-lg-8">
    <form method="post" action=".">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">文章标题</label>
            <input class="form-control" type="text" name="title" id="title" value="{{ post.title }}">
        </div>
        <div class="form-group">
            <label for="body">文章正文</label>
            <textarea class="form-control" type="text" name="body" id="body" rows="12">{{ post.body }}</textarea>
        </div>
        <div class="form-group">
            <label for="topic">标签</label>
            <input class="form-control" type="text" name="topic" id="topic" value="{% for tag in post.topic.all %}{{ tag }},{% endfor %}">
        </div>
        <div class="form-group">
            <label for="topic">栏目</label>
            <select class="form-control" id="column" name="column">
                <option value="none">请选择栏目</option>
                {% for column in columns %}
                <option value="{{ column.id }}">{{ column }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">提交</button>
        </div>
    </form>
    </div>
{% endblock %}

templates/blog/topic.html
{% extends "blog/base.html" %}
{% block detail %}
<div class="col-9">
    {% for column in columns %}
    <a class="breadcrumb" href="{% url 'jimblog:all' %}?search=&column={{ column.id }}&topic=" style="background-color: white; font-size: xx-large; font-family: 'Microsoft Sans Serif', Tahoma, Arial, Verdana, Sans-Serif; color: #75715e">{{ column.title }}</a>
    {% endfor %}
</div>
{% endblock %}